stages:
  - test
  - build

run_tests:
  stage: test
  script:
    - ./gradlew test
  after_script:
    - java -version
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports
    when: always

run_plugin_verifier:
  stage: test
  script:
    - ./gradlew runPluginVerifier
  after_script:
    - java -version
  artifacts:
    paths:
      - build/reports
    when: always

build:
  stage: build
  script:
    - ./gradlew buildPlugin
  artifacts:
    paths:
      - build/libs/odoo_plugin-*.jar
      - "build/distributions/Odoo Autocompletion Support-*.jar"