stages:
  - test
  - build

run_tests:
  stage: test
  script:
    - AT_WTIOIT_PYCHARM_PLUGIN_testVersion=$VERSION AT_WTIOIT_PYCHARM_PLUGIN_testType=$TYPE ./gradlew test
  after_script:
    - java -version
  parallel:
    matrix:
      - TYPE: "PC" # PyCharm Community
        # we should still be run-time compatible, but are not compile-time compatible
        VERSION: [ "2021.2.4", "2021.3.3", "2022.1.4", "2022.2.3" ]
      - TYPE: "PY" # PyCharm Professional
        VERSION: [ "2021.2.4", "2021.3.3", "2022.1.4", "2022.2.3" ]
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports
    when: always

verify_plugin:
  stage: test
  script:
    - ./gradlew verifyPlugin
  after_script:
    - java -version

plugin_verifier:
  stage: test
  script:
    - ./gradlew runPluginVerifier
  after_script:
    - java -version
  artifacts:
    paths:
      - build/reports/pluginVerifier/
    when: always

build:
  stage: build
  script:
    - ./gradlew buildPlugin
  artifacts:
    paths:
      - build/libs/odoo_plugin-*.jar
      - "build/distributions/Odoo Autocompletion Support-*.jar"