#!/usr/bin/env bash
for version in "2021.2" "2021.2.4" \
 "2021.3" "2021.3.3" \
 "2022.1" "2022.1.4"\
 "2022.2" "2022.2.5" \
 "2023.1" "2023.1.4" \
 "2023.2" "2023.2.3"; do
  AT_WTIOIT_PYCHARM_PLUGIN_testVersion=$version
  export AT_WTIOIT_PYCHARM_PLUGIN_testVersion
  for type in "PC" "PY" "IC" "IU"; do
    AT_WTIOIT_PYCHARM_PLUGIN_testType=$type
    export AT_WTIOIT_PYCHARM_PLUGIN_testType
    ./gradlew test
  done
done