#!/usr/bin/env bash
for version in "2019.2" "2019.3" "2020.1" "2020.2" "2ß20.3" "2021.1" "2021.2" "2021.2.1" "2021.2.2" "2021.2.3" "2021.2.4" "2021.3" "2021.3.1" "2021.3.2"; do
  AT_WTIOIT_PYCHARM_PLUGIN_testVersion=$version
  export AT_WTIOIT_PYCHARM_PLUGIN_testVersion
  for type in "PC" "PY" "IC" "IU"; do
    AT_WTIOIT_PYCHARM_PLUGIN_testType=$type
    export AT_WTIOIT_PYCHARM_PLUGIN_testType
    ./gradlew test
  done
done